import type { Metadata } from 'next';
import { Inter, Roboto_Condensed } from 'next/font/google';
import './globals.css';

const inter = Inter({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-inter',
});
const robotoCondensed = Roboto_Condensed({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-roboto-condensed',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} ${robotoCondensed.variable}`}>
				{children}
			</body>
		</html>
	);
}
